version: '3.7'
services:
  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - 3000:3000
    environment:
      - GRPC_PORT=3000

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - 3001:3001
    environment:
      - GRPC_PORT=3001

  presidio-sandbox:
    image: @project.name@:@project.version@
    depends_on:
      - presidio-analyzer
      - presidio-anonymizer
    ports:
      - 8080:8080
    environment:
      - APP_SERVER_PORT=8080
      - ANALYZER_HOST=presidio-analyzer
      - ANALYZER_PORT=3000
      - ANONYMIZER_HOST=presidio-anonymizer
      - ANONYMIZER_PORT=3001
